# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cc4cfc515c02fec46d646ef1767d0b8e143eb50b4b21dc6622cb2b32693998f207bb028ba68def47f2a622f27f059e13f60dc9f6bd37750fb5b7e50098cf443

test:
  secret_key_base: c9e8cdf37e58ffc9cd166f5248de027731379c65ccd260faf1c08002b65fd86056dc9e3ca6435029b3cf51caa28db20d09ca7a45fb4e798e767a4d2cb9c95666

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
